### Variables 
@apiurl = http://localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1NzMyMjc2LCJleHAiOjE3NTU3NTYyNzZ9.LGjpxVd552Y5pJsqe_BwtJr59V-Y6C5YxzTX7v9TadE

### Health
GET {{apiurl}}/health HTTP/1.1
Content-Type: application/json


### Registrar usuario Portal
POST {{apiurl}}/auth/register HTTP/1.1
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
   "name": "User01",
   "email":"user01@gmail.com",
   "password":"12341234"
}

### Verificar e-mail usuário portal
POST {{apiurl}}/auth/verify-email?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc1NTY2MDYzNiwiZXhwIjoxNzU1NzQ3MDM2fQ.POTvvwkNaIhDOVWzFuWpZEjYgpFIKZ8NlEkBCRzx4Gc HTTP/1.1
Content-Type: application/json

### Login Portal
POST {{apiurl}}/auth/login HTTP/1.1
Content-Type: application/json

{
   "email":"user01@gmail.com",
   "password":"12341234"
}

### Buscar perfil
GET {{apiurl}}/auth/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### Esqueci minha senha portal
POST {{apiurl}}/auth/forget-password HTTP/1.1
Content-Type: application/json

{
   "email":"user01@gmail.com"
}

### Resetar a senha portal
POST {{apiurl}}/auth/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc1NTY2MTAzMCwiZXhwIjoxNzU1NjY0NjMwfQ.vRfLG3m9xxKNv9lFYoImsYTkMvQ6olL2PUUNgWJi0CI
Content-Type: application/json

{
   "newPassword":"12341234"
}

### Logout  Portal
POST {{apiurl}}/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}